/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/house/scene.gltf --transform
Author: natsuboy304 (https://sketchfab.com/natsuboy304)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/anime-style-home-c8f9d54f9b48447dad0197e1859f42c1
Title: Anime style home
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Empty001_74">
            <group name="Ac_0" position={[-7.376, 32.214, 19.744]} rotation={[0, 0, -Math.PI]} scale={[-1.227, 0.017, 0.071]}>
              <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material} />
              <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.other_ac} />
            </group>
            <group name="BezierCurve001_2" position={[-9.775, 32.559, 15.511]}>
              <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.wire} />
            </group>
            <group name="book_shelves_3" position={[-13.072, 5.355, 17.417]} scale={[0.897, 0.867, 0.543]}>
              <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.book_shelf} />
            </group>
            <group name="book_shelves001_4" position={[-8.62, 10.412, 7.04]} rotation={[0, Math.PI / 2, 0]} scale={[2.127, 1.838, 0.618]}>
              <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.book_shelf} />
              <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.black_outline} />
            </group>
            <group name="book_shelves003_5" position={[-1.078, 10.412, 2.319]} scale={[-1.705, 1.838, 0.618]}>
              <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.book_shelf} />
              <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.black_outline} />
            </group>
            <group name="Box041001_6" position={[3.217, 41.675, -10.402]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.06, 0.08, 0.06]}>
              <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.wood} />
              <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.translucent} />
            </group>
            <group name="Circle_7" position={[2.824, 43.383, 12.045]} rotation={[Math.PI / 2, 0, 0]} scale={0.388}>
              <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.wire} />
              <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.material_8} />
            </group>
            <group name="Circle001_8" position={[16.763, 38.364, 1.586]} rotation={[0, 0, -Math.PI / 2]} scale={6.328}>
              <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.circle_window} />
            </group>
            <group name="Circle002_9" position={[16.763, 38.364, 1.586]} rotation={[0, 0, -Math.PI / 2]} scale={6.328}>
              <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.curtains} />
            </group>
            <group name="Cube_10" position={[17.118, 23.929, 6.368]} scale={[1, 7.072, 4.548]}>
              <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.wall} />
            </group>
            <group name="Cube001_11" position={[2.562, 13.964, 15.661]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.wall} />
            </group>
            <group name="Cube002_12" position={[-3.257, 34.126, 20.941]} scale={[0.713, 0.387, 0.713]}>
              <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material_12} />
            </group>
            <group name="Cube003_13" position={[23.093, 36.505, -8.682]} rotation={[0, Math.PI / 2, 0]}>
              <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.red_board} />
            </group>
            <group name="Cube005_14" position={[2.562, 22.268, 16.204]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.material_12} />
            </group>
            <group name="Cube006_15" position={[-0.813, 35.338, 11.664]}>
              <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.front_window} />
            </group>
            <group name="Cube007_16" position={[0.991, 10.452, 4.573]} rotation={[0, Math.PI / 2, 0]}>
              <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.back_slide} />
            </group>
            <group name="Cube008_17" position={[13.826, 11.65, 15.561]} rotation={[0, Math.PI / 2, 0]}>
              <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.SIDE_SLIDING_DOOE} />
            </group>
            <group name="Cube009_18" position={[-8.698, 11.65, 15.561]} rotation={[0, Math.PI / 2, 0]}>
              <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.SIDE_SLIDING_DOOE} />
            </group>
            <group name="Cube010_19" position={[3.31, 11.65, 15.561]} rotation={[0, Math.PI / 2, 0]}>
              <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.sliing_door} />
            </group>
            <group name="Cube011_20" position={[4.528, 11.65, 15.761]} rotation={[0, Math.PI / 2, 0]}>
              <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.sliing_door} />
            </group>
            <group name="Cube012_21" position={[18.118, 22.471, 1.902]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.193, 0.403, 0.1]}>
              <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.wood} />
            </group>
            <group name="Cube013_22" position={[17.823, 23.929, 6.368]} scale={[1, 7.072, 4.548]}>
              <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.ouside_window} />
            </group>
            <group name="Cube014_23" position={[17.823, 23.929, -3.081]} scale={[0.687, 4.857, 1.769]}>
              <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.wood} />
            </group>
            <group name="Cube015_24" position={[16.35, 38.548, -8.094]} scale={0.413}>
              <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.metal_pipe} />
            </group>
            <group name="Cube016_25" position={[-15.465, 8.372, 18.203]} scale={[0.172, 0.73, 1]}>
              <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.material_0} />
            </group>
            <group name="Cube017_26" position={[-15.465, 6.152, 18.203]} scale={[0.172, 0.73, 1]}>
              <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.material_0} />
            </group>
            <group name="Cube018_27" position={[-15.465, 3.932, 18.203]} scale={[0.172, 0.73, 1]}>
              <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.material_0} />
            </group>
            <group name="Cube019_28" position={[-0.06, 9.313, 18.203]} scale={[0.172, 1.203, 1]}>
              <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.material_0} />
            </group>
            <group name="Cube020_29" position={[0.768, 3.884, 22.215]} scale={[0.172, 1.203, 1]}>
              <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.material_0} />
            </group>
            <group name="Cube021_30" position={[2.848, 3.884, 22.215]} scale={[0.172, 1.203, 1]}>
              <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material_0} />
            </group>
            <group name="Cube022_31" position={[4.97, 3.884, 22.215]} scale={[0.172, 1.203, 1]}>
              <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.material_0} />
            </group>
            <group name="Cube023_32" position={[6.269, 4.442, 22.419]} scale={[0.172, 0.73, 1]}>
              <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.material_0} />
            </group>
            <group name="Cube024_33" position={[-5.779, 11.758, 3.317]} scale={[0.172, 1.203, 1]}>
              <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.material_0} />
            </group>
            <group name="Cube025_34" position={[-5.779, 7.053, 3.317]} scale={[0.172, 1.203, 1]}>
              <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.material_0} />
            </group>
            <group name="Cube026_35" position={[-4.747, 2.628, 3.317]} scale={[0.172, 1.203, 1]}>
              <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.material_0} />
            </group>
            <group name="Cube027_36" position={[-4.747, 15.432, 3.317]} scale={[0.172, 1.203, 1]}>
              <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.material_0} />
            </group>
            <group name="Cube028_37" position={[-7.587, 11.758, 12.95]} scale={[0.172, 1.203, 1]}>
              <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.material_0} />
            </group>
            <group name="Cube029_38" position={[-7.587, 16.463, 12.95]} scale={[0.172, 1.203, 1]}>
              <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.material_0} />
            </group>
            <group name="Cube030_39" position={[-7.587, 7.053, 12.95]} scale={[0.172, 1.203, 1]}>
              <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.material_0} />
            </group>
            <group name="Cube031_40" position={[-7.587, 3.66, 12.95]} scale={[0.172, 1.203, 1]}>
              <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.material_0} />
            </group>
            <group name="Cube032_41" position={[17.823, 23.929, -3.081]} scale={[0.687, 4.857, 1.769]}>
              <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.glass} />
            </group>
            <group name="Cube033_42" position={[17.118, 11.44, 6.368]} scale={[1, 7.072, 4.548]}>
              <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.bricks} />
            </group>
            <group name="Cube034_43" position={[17.118, 11.44, 6.368]} scale={[1, 7.072, 4.548]}>
              <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.glass} />
            </group>
            <group name="Cube035_44" position={[17.118, 11.44, 6.368]} scale={[1, 7.072, 4.548]}>
              <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.wood} />
            </group>
            <group name="Cube036_45" position={[-12.879, 39.2, 0.662]} scale={[1.866, 5.531, 6.178]}>
              <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.orange_wood} />
            </group>
            <group name="Dustbin_2_Lid_0_46" position={[-15.133, 9.728, -14.362]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.902, 2.902, 0.278]}>
              <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.dustbin} />
            </group>
            <group name="Dustbin_0_47" position={[-15.14, 1.111, -14.362]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.902, 2.902, 0.278]}>
              <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.dustbin} />
            </group>
            <group name="floor_49" position={[2.562, 0.556, 6.368]}>
              <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.floor} />
            </group>
            <group name="guard_50" position={[-1.357, 35.444, 15.129]}>
              <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.wood} />
            </group>
            <group name="NurbsPath001_52" position={[-20.735, 41.031, -21.912]}>
              <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.wire} />
            </group>
            <group name="outside_book_shelf_53" position={[3.619, 5.294, 19.52]} scale={15}>
              <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.orange_wood} />
            </group>
            <group name="pipe_54" position={[18.085, 31.447, 13.824]} scale={[1, 0.705, 1]}>
              <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.metal_pipe} />
            </group>
            <group name="Plane_55" position={[-11.882, 34.661, 0]} scale={[0.292, 1, 4.147]}>
              <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.yellow_wood} />
            </group>
            <group name="Plane001_56">
              <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.glass} />
            </group>
            <group name="Plane004_Plane010_57" position={[-20.982, 22.175, -24.499]} rotation={[Math.PI / 2, 0, 0.836]} scale={21.064}>
              <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.metal_pipe} />
              <mesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials.wire} />
            </group>
            <group name="roof_wood_58" position={[2.642, 49.996, 1.116]}>
              <mesh name="Object_121" geometry={nodes.Object_121.geometry} material={materials.roof} />
            </group>
            <group name="roof003_59" position={[2.725, 50.841, 1.163]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.055}>
              <mesh name="Object_123" geometry={nodes.Object_123.geometry} material={materials.wood} />
              <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.roof} />
            </group>
            <group name="roof004_60" position={[21.377, 28.314, 0.668]} rotation={[Math.PI / 2, 0, 0]} scale={[0.696, 0.847, 0.696]}>
              <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.wood} />
              <mesh name="Object_127" geometry={nodes.Object_127.geometry} material={materials.roof} />
            </group>
            <group name="shadow_saster001_61">
              <mesh name="Object_129" geometry={nodes.Object_129.geometry} material={materials.shader} />
            </group>
            <group name="shelves_for_book_62" position={[-13.072, 7.503, 18.062]} scale={[0.897, 0.867, 0.543]}>
              <mesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials.shelf} />
              <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.black_outline} />
            </group>
            <group name="shelves_for_book001_63" position={[-7.886, 14.966, 7.04]} rotation={[0, Math.PI / 2, 0]} scale={[2.127, 1.838, 0.618]}>
              <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.shelf} />
              <mesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials.black_outline} />
            </group>
            <group name="shelves_for_book003_64" position={[-1.078, 14.966, 3.054]} scale={[-1.705, 1.838, 0.618]}>
              <mesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials.shelf} />
              <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.black_outline} />
            </group>
            <group name="side_restroom_65" position={[11.666, 35.353, 14.564]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.wall} />
            </group>
            <group name="stairs_66" position={[-0.36, 29.589, -21.55]} scale={[1, 1, 7.072]}>
              <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.orange_wood} />
            </group>
            <group name="stairs002_68" position={[7.912, 33.558, -21.319]} scale={[1, 1, 7.072]}>
              <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.wood} />
            </group>
            <group name="stairs006_69" position={[-10.36, 5.618, -27.726]} scale={[0.188, 1, 7.072]}>
              <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.wood} />
            </group>
            <group name="table_70" position={[13.01, 14.966, 7.04]} rotation={[0, -Math.PI / 2, 0]} scale={[-2.127, 1.838, 0.618]}>
              <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.shelf} />
              <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.black_outline} />
            </group>
            <group name="wall_71" position={[6.225, 15.184, 0.165]}>
              <mesh name="Object_151" geometry={nodes.Object_151.geometry} material={materials.floorbwall} />
            </group>
            <group name="window_border_72" position={[1.164, 36.394, 1.869]}>
              <mesh name="Object_153" geometry={nodes.Object_153.geometry} material={materials.wall} />
              <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.floorbwall} />
            </group>
            <group name="wood_02_73" position={[2.562, 46.732, 1.119]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[3.113, 0.28, 0.534]}>
              <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.wood} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
